name: 'Clear Image Cache'
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repo'
        uses: 'actions/checkout@v2'
      - name: 'Set up python'
        uses: 'actions/setup-python@v2'
        with:
          python-version: 3.8
          architecture: x64
      - name: 'Change README'
        run: |-
          python clearer.py
          cat README.md
      - name: 'Commit and push'
        run: |-
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "MadREADMEBot"
          git add -A
          git commit -m "Force Reset Badges" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/MadAvidCoder/MadAvidCoder.git HEAD:main